---
title: "E18 mouse brain, correlation LONG / SHORT read profiling"
author: "K.Lebrigand, R.Waldmann"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---

# Loading illu1141c.rds

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

source("00.import.R")

illu1141 <- readRDS("illu1141c.rds")
DimPlot(object = illu1141, reduction = "tsne", label = FALSE, pt.size = 2)

100*sum(illu1141@meta.data$nCount_ISOG)/sum(illu1141@meta.data$nCount_RNA)
100*sum(illu1141@meta.data$nFeature_ISOG)/sum(illu1141@meta.data$nFeature_RNA)

median(illu1141@meta.data$nCount_ISOG)
median(illu1141@meta.data$nCount_RNA)
median(illu1141@meta.data$nFeature_ISOG)
median(illu1141@meta.data$nFeature_RNA)

```

# Illumina molecules profiled with Nanopore reads (190 cells)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

sub190 <- subset(illu1141, subset = sample==1)
100*sum(sub190@meta.data$nCount_ISOG)/sum(sub190@meta.data$nCount_RNA)
100*sum(sub190@meta.data$nFeature_ISOG)/sum(sub190@meta.data$nFeature_RNA)

```

# Illumina molecules profiled with Nanopore reads (951 cells)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

sub951 <- subset(illu1141, subset = sample==3)
100*sum(sub951@meta.data$nCount_ISOG)/sum(sub951@meta.data$nCount_RNA)
100*sum(sub951@meta.data$nFeature_ISOG)/sum(sub951@meta.data$nFeature_RNA)

```

# Correlation plots illumina/Nanopore (r²)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

#pdf("Correlation.plots.pdf", width=10, height=8, useDingbats=FALSE)

ggplot(data=illu1141@meta.data, aes(x=nCount_RNA,y=nCount_ISOG)) +  geom_point(shape = 21, colour = "black", fill = col[as.numeric(illu1141@meta.data$sample)]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
      ggtitle("Nanopore / Illumina nUMIs (190 + 951 cells)") +
       geom_abline(slope=1, intercept=-15, linetype=3) +
      labs(x="Illumina",y="Nanopore")

x <- cor.test(illu1141@meta.data$nCount_RNA, illu1141@meta.data$nCount_ISOG, method="pearson")$estimate
x*x

ggplot(data=illu1141@meta.data, aes(x=nFeature_RNA,y=nFeature_ISOG)) +  geom_point(shape = 21, colour = "black", fill = col[as.numeric(illu1141@meta.data$sample)]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
      ggtitle("Nanopore / Illumina nGenes (190 + 951cells)") +
      geom_abline(slope=1, intercept=-15, linetype=3) +
      labs(x="Illumina",y="Nanopore")

x <- cor.test(illu1141@meta.data$nFeature_RNA, illu1141@meta.data$nFeature_ISOG, method="pearson")$estimate
x*x

plot1 <- ggplot(data=illu1141@meta.data, aes(nCount_RNA)) + 
                geom_histogram(breaks=seq(0, 20000, by = 500),col="black",aes(fill=nGene), fill="lightsteelblue3") + 
                scale_fill_gradient("Count", low = "green", high = "red") +
                labs(title="Illumina nUMI") +
                labs(x="nUMI", y="Cells")

plot2 <- ggplot(data=illu1141@meta.data, aes(nCount_ISOG)) + 
                geom_histogram(breaks=seq(0, 20000, by = 500),col="black",aes(fill=nGene),fill="lightsteelblue3") + 
                scale_fill_gradient("Count", low = "green", high = "red") +
                labs(title="Nanopore nUMI") + 
                labs(x="nUMI", y="Cells")

plot_grid(plot1, plot2)

plot1 <- ggplot(data=illu1141@meta.data, aes(nFeature_RNA)) + 
                geom_histogram(breaks=seq(0, 5000, by = 100),col="black",aes(fill=nGene),fill="lightsteelblue3") + 
                scale_fill_gradient("Count", low = "green", high = "red") +
                labs(title="Illumina nGene") + 
                labs(x="nGene", y="Cells")

plot2 <- ggplot(data=illu1141@meta.data, aes(nFeature_ISOG)) + 
                geom_histogram(breaks=seq(0, 5000, by = 100),col="black",aes(fill=nGene),fill="lightsteelblue3") + 
                scale_fill_gradient("Count", low = "green", high = "red") +
                labs(title="Nanopore nGene") + 
                labs(x="nGene", y="Cells")

plot_grid(plot1, plot2)

#dev.off()

```

# Correlation Illumina / Nanopore (r)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

common.cells <- rownames(illu1141@meta.data)
common.genes <- intersect(rownames(illu1141@assays$RNA@data), rownames(illu1141@assays$ISOG@data))

df <- data.frame()
for (i in (1:length(common.cells))){
  t <- data.frame(illu1141@assays$RNA@data[common.genes,common.cells[i]], illu1141@assays$ISOG@data[common.genes,common.cells[i]])
  colnames(t) <- c("illu","nano")
  df <- rbind(df, data.frame("Illu/ONT same cell",cor.test(t$illu, t$nano)$estimate))
}
colnames(df) <- c("type","cor")
rownames(df) <- c()

df2 <- data.frame()
for (i in (1:length(common.cells))){
  #print (i)
  random <- sample(1:length(common.cells), 1, replace=T)
  
  for (j in (1:length(random))){
    if(i != random[j]){
      
      t <- data.frame(illu1141@assays$RNA@data[common.genes,common.cells[random[j]]], illu1141@assays$ISOG@data[common.genes,common.cells[i]])
      colnames(t) <- c("illu","nano")
      df2 <- rbind(df2, data.frame("Illu/ONT different cell",cor.test(t$illu, t$nano)$estimate))
    }
  }
}
colnames(df2) <- c("type","cor")
rownames(df2) <- c()

```
Nanopore/Illumina same cell
```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}
median(df$cor)

```
Nanopore/Illumina different cell
```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}
median(df2$cor)
```

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=12}

#pdf("/home/lebrigand/10x_rainer/figures/Correlation.plots.boxplots.pdf", width=10, height=8, useDingbats=FALSE)
whole <- rbind(df,df2)
ggplot(whole, aes(x=type, y=cor, fill=type)) +
  geom_boxplot()+
  theme_classic()
#dev.off()

```

# Session Info

```{r sessinf}
sessionInfo()
```
