---
title: "E18 mouse brain, 03 - ISO integration"
author: 'K.Lebrigand, R.Waldmann'
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    code_folding: none
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  cache.lazy = FALSE,
  tidy = TRUE
)
```

# Loading data

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

#setwd("/data/10x_data/10x_rainer/")
source("00.import.R")

s190 <- readRDS("output/s190.rds")
s951 <- readRDS("output/s951.rds")

```

# Integration (RNA)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

anchors <- FindIntegrationAnchors(object.list = c(s190, s951), assay=c("ISO","ISO"), dims = 1:30)
s1141 <- IntegrateData(anchorset = anchors, dims = 1:30)
DefaultAssay(object = s1141) <- "integrated"
s1141 <- ScaleData(object = s1141, verbose = FALSE)
s1141 <- RunPCA(object = s1141, npcs = 30, verbose = FALSE)
ElbowPlot(object = s1141)

s1141 <- RunTSNE(object = s1141, reduction = "pca", dims = 1:11)
s1141 <- FindNeighbors(object = s1141, do.plot=TRUE, dims = 1:11)
s1141 <- FindClusters(object = s1141, resolution=0.8)

#pdf("clusters.pdf", width=10, height=8, useDingbats=FALSE)
DimPlot(object = s1141, reduction = "tsne", group.by = "state")
DimPlot(object = s1141, reduction = "tsne")
#dev.off()

s1141 <- NormalizeData(object = s1141, assay = "ISOG")
s1141 <- scale_my_data(s1141, assay="ISOG")
s1141 <- NormalizeData(object = s1141, assay = "ISO")
s1141 <- scale_my_data(s1141, assay="ISO")
s1141 <- NormalizeData(object = s1141, assay = "JUNC")
s1141 <- scale_my_data(s1141, assay="JUNC")
s1141 <- NormalizeData(object = s1141, assay = "EDIT")
s1141 <- scale_my_data(s1141, assay="EDIT")

```

# Clusters re-labelling, saving .rds file

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

new.cluster.ids <- c("imature Glutamatergic","imature GABAergic","mature Glutamatergic","mature GABAergic", "radial glia + intermediate progenitor", "cycling radial glia","mature Glutamatergic","mature Glutamatergic","Cajal-Retzius")
names(x = new.cluster.ids) <- levels(x = s1141)
s1141 <- RenameIdents(object = s1141, new.cluster.ids)

my_levels <- c("cycling radial glia","radial glia + intermediate progenitor", "imature Glutamatergic", "mature Glutamatergic","imature GABAergic","mature GABAergic", "Cajal-Retzius")
# Relevel object@ident
s1141@active.ident <- factor(x = s1141@active.ident, levels = my_levels)
DimPlot(object = s1141, reduction = "tsne", label = FALSE, pt.size = 2)

rna1141 <- readRDS("output/rna.labels.rds")
s1141[['illumina.ident']] <- rna1141@active.ident

DimPlot(object = s1141, reduction = "tsne", group.by="illumina.ident", label = FALSE, pt.size = 2)
saveRDS(s1141, "output/iso.labels.rds")

pdf("figures/fig.2e.pdf", width=12, height=12, useDingbats=FALSE)
DimPlot(object = s1141, reduction = "tsne", group.by="illumina.ident", label = FALSE, pt.size = 2)
dev.off();

```

# Session Info

```{r sessinf}
sessionInfo()
```

