---
title: "E18 mouse brain, Figures"
author: "K.Lebrigand, R.Waldmann"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---

# Loading illu1141c.rds

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

source("00.import.R")
illu1141 <- readRDS("illu1141c.rds")

```

# Correlation plots illumina/Nanopore (r²)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

#pdf("Correlation.plots.pdf", width=10, height=8, useDingbats=FALSE)

col=c("red","","blue")

pdf("figures/fig.1e.pdf", width=10, height=8, useDingbats=FALSE)
ggplot(data=illu1141@meta.data, aes(x=nFeature_RNA,y=nFeature_ISOG)) +  geom_point(shape = 21, colour = "black", fill = col[as.numeric(illu1141@meta.data$sample)]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
      ggtitle("Fig.1e - Genes (r=0.993, r2=0.988") +
      #geom_abline(slope=1, intercept=-15, linetype=3) +
      labs(x="Illumina",y="Nanopore")
dev.off()
x <- cor.test(illu1141@meta.data$nFeature_RNA, illu1141@meta.data$nFeature_ISOG, method="pearson")$estimate
x*x


pdf("figures/fig.1f.pdf", width=10, height=8, useDingbats=FALSE)
ggplot(data=illu1141@meta.data, aes(x=nCount_RNA,y=nCount_ISOG)) +  geom_point(shape = 21, colour = "black", fill = col[as.numeric(illu1141@meta.data$sample)]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
      ggtitle("Fig.1f - UMIs (r=0.994, r2=0.988") +
      #geom_abline(slope=1, intercept=-15, linetype=3) +
      labs(x="Illumina",y="Nanopore")

dev.off()
x <- cor.test(illu1141@meta.data$nCount_RNA, illu1141@meta.data$nCount_ISOG, method="pearson")$estimate
x*x


common.cells <- rownames(illu1141@meta.data)
common.genes <- intersect(rownames(illu1141@assays$RNA@data), rownames(illu1141@assays$ISOG@data))

df <- data.frame()
for (i in (1:length(common.cells))){
  t <- data.frame(illu1141@assays$RNA@data[common.genes,common.cells[i]], illu1141@assays$ISOG@data[common.genes,common.cells[i]])
  colnames(t) <- c("illu","nano")
  df <- rbind(df, data.frame("Illu/ONT same cell (r=0.94)",cor.test(t$illu, t$nano)$estimate))
}
colnames(df) <- c("type","cor")
rownames(df) <- c()

df2 <- data.frame()
for (i in (1:length(common.cells))){
  #print (i)
  random <- sample(1:length(common.cells), 5, replace=T)
  
  for (j in (1:length(random))){
    if(i != random[j]){
      
      t <- data.frame(illu1141@assays$RNA@data[common.genes,common.cells[random[j]]], illu1141@assays$ISOG@data[common.genes,common.cells[i]])
      colnames(t) <- c("illu","nano")
      df2 <- rbind(df2, data.frame("Illu/ONT different cell (r=0.58)",cor.test(t$illu, t$nano)$estimate))
    }
  }
}
colnames(df2) <- c("type","cor")
rownames(df2) <- c()

```
Nanopore/Illumina same cell
```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}
median(df$cor)

```
Nanopore/Illumina different cell
```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}
median(df2$cor)
```

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=12}

pdf("figures/fig.1g.pdf", width=10, height=8, useDingbats=FALSE)
whole <- rbind(df,df2)
ggplot(whole, aes(x=type, y=cor, fill=type)) +
  geom_boxplot()+
  theme_classic()
dev.off()


pdf("figures/fig.1h.pdf", width=10, height=8, useDingbats=FALSE)
DimPlot(object = illu1141, reduction = "tsne", group.by="illumina.ident")
dev.off()

iso1141 <- readRDS("iso1141c.rds")
pdf("figures/fig.1i.pdf", width=10, height=8, useDingbats=FALSE)
DimPlot(object = iso1141, reduction = "tsne", group.by="illumina.ident")
dev.off()


```

# fig.2abc+d

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=12}

pdf("figures/fig.2abc.pdf", width=24, height=6, useDingbats=FALSE)
FeaturePlot(object = illu1141, features = c("Clta-ENSMUST00000107849.9","Clta-ENSMUST00000170241.7"), blend=TRUE, cols=c("grey","red"), reduction="tsne", ncol=3)
dev.off()

DefaultAssay(object = illu1141) <- "RNA"
pdf("figures/fig.2d.pdf", width=6, height=6, useDingbats=FALSE)
FeaturePlot(object = illu1141, features = c("Clta"), cols=custom.pal, reduction="tsne")
FeaturePlot(object = illu1141, features = c("Clta"), cols=c("grey","red"), reduction="tsne")
dev.off()

```

# supl.fig.4abc+d

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=12}

pdf("figures/fig.4abc.pdf", width=24, height=6, useDingbats=FALSE)
FeaturePlot(object = illu1141, features = c("Myl6-ENSMUST00000218127.1","Myl6-ENSMUST00000164181.1"), blend=TRUE, cols=c("grey","red"), reduction="tsne", ncol=3)
dev.off()

DefaultAssay(object = illu1141) <- "RNA"
pdf("figures/fig.4d.pdf", width=6, height=6, useDingbats=FALSE)
FeaturePlot(object = illu1141, features = c("Myl6"), cols=custom.pal, reduction="tsne")
FeaturePlot(object = illu1141, features = c("Myl6"), cols=c("grey","red"), reduction="tsne")
dev.off()

```

# supl.fig.3b

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=12}

pdf("figures/sup.fig.3b.pdf", width=24, height=8, useDingbats=FALSE)

DefaultAssay(object = illu1141) <- "ISO"
general <- c('Clta','Pkm','Gpm6b','Ergic3','Myl6','Akap9','Chchd3','Dpysl3','Sh3glb1','Rps24','Eef1d','Kif1b','Cdc42','Zfand6','Faim','Bin1','Sft2d1','Rtn4','Elavl2','Ewsr1','Rpn2','Gnas','Bnip2','Meaf6','Borcs8','Smarcb1','Evl','Vps29','Tpd52l2','Exoc7','Tecr','Ap1s2','Tcf4','Psap','Nasp','Chtop','Pantr1','Sh3glb2','Atp5c1','Erp29','Rpl13a')

lst <- c()
genes.liste <- c('Clta','Pkm','Gpm6b','Ergic3','Myl6','Akap9','Chchd3','Dpysl3','Sh3glb1','Rps24')
for (i in (1:length(genes.liste))){
  x <- rownames(illu1141@assays$ISO@counts)[grep(paste("^",genes.liste[i],"-",sep=""), rownames(illu1141@assays$ISO@counts))]
  lst <- c(lst,x)
}
print(DotPlot(object = illu1141, features = lst, reduction="tsne", scale.max = 100) + theme(axis.text.x = element_text(angle = 90, hjust = 1))) # RotatedAxis

lst <- c()
genes.liste <- c('Eef1d','Kif1b','Cdc42','Zfand6','Faim','Bin1','Sft2d1','Rtn4','Elavl2','Ewsr1')
for (i in (1:length(genes.liste))){
  x <- rownames(illu1141@assays$ISO@counts)[grep(paste("^",genes.liste[i],"-",sep=""), rownames(illu1141@assays$ISO@counts))]
  lst <- c(lst,x)
}
print(DotPlot(object = illu1141, features = lst, reduction="tsne", scale.max = 100) + theme(axis.text.x = element_text(angle = 90, hjust = 1))) # RotatedAxis

lst <- c()
genes.liste <- c('Rpn2','Gnas','Bnip2','Meaf6','Borcs8','Smarcb1','Evl','Vps29','Tpd52l2','Exoc7','Tecr')
for (i in (1:length(genes.liste))){
  x <- rownames(illu1141@assays$ISO@counts)[grep(paste("^",genes.liste[i],"-",sep=""), rownames(illu1141@assays$ISO@counts))]
  lst <- c(lst,x)
}
print(DotPlot(object = illu1141, features = lst, reduction="tsne", scale.max = 100) + theme(axis.text.x = element_text(angle = 90, hjust = 1))) # RotatedAxis

lst <- c()
genes.liste <- c('Ap1s2','Tcf4','Psap','Nasp','Chtop','Pantr1','Sh3glb2','Atp5c1','Erp29','Rpl13a')
for (i in (1:length(genes.liste))){
  x <- rownames(illu1141@assays$ISO@counts)[grep(paste("^",genes.liste[i],"-",sep=""), rownames(illu1141@assays$ISO@counts))]
  lst <- c(lst,x)
}
print(DotPlot(object = illu1141, features = lst, reduction="tsne", scale.max = 100) + theme(axis.text.x = element_text(angle = 90, hjust = 1))) # RotatedAxis

DefaultAssay(object = illu1141) <- "RNA"
print(DotPlot(object = illu1141, features = general, reduction="tsne", scale.max = 100, cols = c("lightgrey", "red")) + theme(axis.text.x = element_text(angle = 90, hjust = 1))) # RotatedAxis
dev.off()


```

# Session Info

```{r sessinf}
sessionInfo()
```
